force-app/main/default/objects/Customer_Vehicle_Info__c/Customer_Vehicle_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle Information</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Vechiles Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Vehicle_Info__c/fields/Customer_address__c.field-meta.xml
<CustomField>
    <fullName>Customer_address__c</fullName>
    <inlineHelpText>enter customer address</inlineHelpText>
    <label>Customer address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Vehicle_Info__c/fields/Customer_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Mobile_Number__c</fullName>
    <inlineHelpText>9000000000</inlineHelpText>
    <label>Customer Mobile Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer_Vehicle_Info__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>name of the customer</description>
    <label>Customer Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Vehicle_Info__c/fields/Premise_Name__c.field-meta.xml
<CustomField>
    <fullName>Premise_Name__c</fullName>
    <inlineHelpText>enter building or community name</inlineHelpText>
    <label>Premise Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Vehicle_Info__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <description>type of the vehicle</description>
    <label>Vehicle Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hatch-Back</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>MPV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerVehicleInfoExtension.cls
public with sharing class CustomerVehicleInfoExtension {
    public ApexPages.StandardController vehicleController { get; set; }
    
    public Customer_Vehicle_Info__c vehicleInfo {get; set;}
    public Id selectedSubsId{get;set;}

    public CustomerVehicleInfoExtension(ApexPages.StandardController standardController)
     {
        this.vehicleController = standardController;

        vehicleInfo =(Customer_Vehicle_Info__C)standardController.getRecord();
    }
   
   

  
    

    public PageReference SaveDetail()
    {
        system.debug(vehicleInfo);
        Customer_Vehicle_Info__C InsertVehicleDetails = new Customer_Vehicle_Info__C();
        InsertVehicleDetails.Id=vehicleInfo.Id;
        InsertVehicleDetails.Name=vehicleInfo.Name;
        InsertVehicleDetails.Vehicle_Type__c=vehicleInfo.Vehicle_Type__c;
        InsertVehicleDetails.Customer_Name__c=vehicleInfo.Customer_Name__c;
        InsertVehicleDetails.Customer_Mobile_Number__c=vehicleInfo.Customer_Mobile_Number__c;
        InsertVehicleDetails.Customer_Email__c=vehicleInfo.Customer_Email__c;
        InsertVehicleDetails.Premise_Name__c=vehicleInfo.Premise_Name__c;
        InsertVehicleDetails.Customer_address__c=vehicleInfo.Customer_address__c;
        upsert InsertVehicleDetails;
        return new PageReference('/apex/VehicleListHomePage');

    }

    public PageReference HomepageRedirection() 
    {
       return new PageReference('/apex/VehicleListHomePage');
      }

      public void cancelDetail()
      {
        
      }


      public PageReference showSubsDetails() 
      {
         return new PageReference('/apex/subscriptionDetailPage?id='+selectedSubsId);
    } 

    public PageReference newsubscription() 
    {

        PageReference Blanksubscription =new PageReference('/apex/BlanksubscriptionDetailPage');
        Blanksubscription.getParameters().put('vehicleName', vehicleInfo.Name);
        Blanksubscription.getParameters().put('vehicleId', vehicleInfo.Id);
        return Blanksubscription;
  } 


}