force-app/main/default/objects/Customer_Vehicle_Info__c/Customer_Vehicle_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle Information</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Vechiles Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>subscription details of each vehicle</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Subscription_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_date__c</fullName>
    <inlineHelpText>enter the start date of subscription</inlineHelpText>
    <label>Subscription Start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Subscription Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Month</fullName>
                <default>true</default>
                <label>1 Month</label>
            </value>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>1 Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Number__c</fullName>
    <label>Vehicle Number</label>
    <referenceTo>Customer_Vehicle_Info__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BlankSubscriptionDetailPageExtension.cls
public with sharing class BlankSubscriptionDetailPageExtension {

    
    public Subscription__c Subscription {get; set;}
    public Customer_Vehicle_Info__C vehicle {get; set;}

    public BlankSubscriptionDetailPageExtension()
    {
        this.Subscription=new Subscription__c();
        this.vehicle=new Customer_Vehicle_Info__C();
        vehicle.Id=ApexPages.currentPage().getParameters().get('vehicleId');
        vehicle.Name=ApexPages.currentPage().getParameters().get('vehicleName');
        this.Subscription.Vehicle_Number__r=vehicle;
        //this.Subscription.Vehicle_Number__r.Name=vehicle.Name;

    }
    
    public PageReference VehiclepageRedirection() 
    {
        
        
        if (vehicle.Id != null)
        {
            return new PageReference('/apex/VehicleDetail?id='+vehicle.Id); 
        }
        else 
            {
                return new PageReference('/apex/VehicleDetail');
            }
        
      
      }

      public PageReference HomepageRedirection() 
    {
       return new PageReference('/apex/VehicleListHomePage');
      }

      public PageReference SaveDetail()
    {
        Subscription__c subs = new Subscription__c();
        //Customer_Vehicle_Info__C vh = new Customer_Vehicle_Info__C();
        subs.subscription_start_date__C=Subscription.subscription_start_date__c;
        subs.Subscription_Type__C=Subscription.Subscription_Type__c;
        //vh.id=vehicle.Id;
        //vh.Name=vehicle.Name;
        //subs.Vehicle_Number__r=vh;
        subs.Vehicle_Number__c=vehicle.Id;
        insert subs;
        return new PageReference('/apex/VehicleDetail?id='+vehicle.Id);
    }

    public void cancelDetail()
    {

    }
   
    
}