force-app/main/default/objects/Customer_Vehicle_Info__c/Customer_Vehicle_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle Information</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Vechiles Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Vehicle_Info__c/fields/Customer_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Mobile_Number__c</fullName>
    <inlineHelpText>9000000000</inlineHelpText>
    <label>Customer Mobile Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer_Vehicle_Info__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>name of the customer</description>
    <label>Customer Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Vehicle_Info__c/fields/Premise_Name__c.field-meta.xml
<CustomField>
    <fullName>Premise_Name__c</fullName>
    <inlineHelpText>enter building or community name</inlineHelpText>
    <label>Premise Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CutomerVehicleClass.cls
public with sharing class CutomerVehicleClass 
{
    public Id selectedVehicleId{get;set;}
    public ApexPages.StandardSetController vehicleListController { get; set; }
    public String searchKeyword {get;set;}
    public List<Customer_Vehicle_Info__c> vehicleInfoList {get;set;}
    public CutomerVehicleClass(ApexPages.StandardSetController controller) {
        this.vehicleListController = controller;
    }

    
    public PageReference showVehicleDetails() {
        return new PageReference('/apex/VehicleDetail?id=' + selectedVehicleId);
    }

    public void performSearch() {
        if(searchKeyword.length()!=0)
        {
            String searchQuery = 'SELECT Id, Name, Customer_Name__c, Customer_Mobile_Number__c, Premise_Name__c FROM Customer_Vehicle_Info__c WHERE Name LIKE \'%' + searchKeyword + '%\'';
            vehicleInfoList = Database.query(searchQuery);
            
        }
        
    }
}