force-app/main/default/objects/Customer_Vehicle_Info__c/Customer_Vehicle_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle Information</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Vechiles Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>subscription details of each vehicle</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Subscription_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_date__c</fullName>
    <inlineHelpText>enter the start date of subscription</inlineHelpText>
    <label>Subscription Start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Subscription Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Month</fullName>
                <default>true</default>
                <label>1 Month</label>
            </value>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>1 Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Number__c</fullName>
    <label>Vehicle Number</label>
    <referenceTo>Customer_Vehicle_Info__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SubscriptionDetailPageExtension.cls
public with sharing class SubscriptionDetailPageExtension {
    public ApexPages.StandardController SubscriptionController { get; set; }
    
    public Subscription__c SubInfo {get; set;}
    public SubscriptionDetailPageExtension(ApexPages.StandardController standardController) 
    {
        this.SubscriptionController = standardController;

        SubInfo =(Subscription__c)standardController.getRecord();
    }
    public PageReference VehiclepageRedirection() 
    {
        
        string vehicleId=SubInfo.Vehicle_Number__r.Id;
       return new PageReference('/apex/VehicleDetail?id='+vehicleId);
      }

      public PageReference HomepageRedirection() 
    {
       return new PageReference('/apex/VehicleListHomePage');
      }
    public PageReference SaveDetail()
    {
        Subscription__c InsertSubscriptionDetails = new Subscription__c();
        InsertSubscriptionDetails.Id=SubInfo.Id;
        InsertSubscriptionDetails.subscription_start_date__C=SubInfo.subscription_start_date__C;
        InsertSubscriptionDetails.Subscription_Type__C=SubInfo.Subscription_Type__C;
        InsertSubscriptionDetails.Subscription_Status__C=SubInfo.Subscription_Status__C;
        
        upsert InsertSubscriptionDetails;

        return new PageReference('/apex/VehicleDetail?id='+SubInfo.Vehicle_Number__r.Id);


    }

    public void cancelDetail()
    {

    }
    
  
}