force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>subscription details of each vehicle</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Subscription_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_date__c</fullName>
    <inlineHelpText>enter the start date of subscription</inlineHelpText>
    <label>Subscription Start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Subscription Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Month</fullName>
                <default>true</default>
                <label>1 Month</label>
            </value>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>1 Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubscriptionTriggerHandeler.cls
public with sharing class SubscriptionTriggerHandeler {
   
    public static void SubscriptionUpdate()
    {
        List<Subscription__C> sList= new List<Subscription__C>();
        sList = Trigger.New;
        for(Subscription__C subscription:sList)
        {
             if(subscription.Subscription_Type__c=='1 Day')
             {
                subscription.Subscription_End_Date__c = subscription.Subscription_Start_date__c+1;
                
             }
             else if(subscription.Subscription_Type__c=='1 Month')
             {
                subscription.Subscription_End_Date__c = subscription.Subscription_Start_date__c+30;
             }
            
             if (subscription.Subscription_End_Date__c > system.now())
             {
                subscription.Subscription_Status__c='Active';
             }
             else 
             {
                subscription.Subscription_Status__c='Inactive';
                
             }
            

        }
    }
}